### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-DirectorySelection#9]
It has an empty gradle file:

https://github.com/googlesamples/android-DirectorySelection/blob/master/build.gradle

So I get this:

![image](https://user-images.githubusercontent.com/5357526/54640101-a88f6e00-4a97-11e9-9dc2-15bfd76707ba.png)

**Comment by std829** [comment]
[the gradle file for the application module exists](https://github.com/googlesamples/android-DirectorySelection/blob/master/Application/build.gradle). You're probably getting the error because you don't have the same Build tools version. Have you tried updating those as per the suggestions you're getting at the end of the error message? It worked on mine when I sync'ed it properly.

**Comment by AndroidDeveloperLB** [comment]
@std829 Look :

![image](https://user-images.githubusercontent.com/5357526/56894392-62fa9380-6a8e-11e9-9b42-bc5f279e2fa2.png)

But for some reason, now I can run it:

![image](https://user-images.githubusercontent.com/5357526/56894549-eae09d80-6a8e-11e9-953b-30f19b3d02de.png)

How come?

**Comment by std829** [comment]
You will notice that there are two gradle files in the project. As I mentioned before, the gradle for the applications module is not empty and is responsible for setting up teh project. Maybe you have updated the gradle tools since you last tried to run it and that is why the build was successful this time around.

**Comment by AndroidDeveloperLB** [comment]
I don't know. It's weird. Why the other gradle file is empty? And how come the project can work with it being empty?
